### ISSUE TITLE
Redirect http traffic for api to https does not work

### ISSUE THREAD

**Issue by rolu01** [onify/install#5]
If I go to http://oni-demo1-apo.onify.io/documentation I get `404 page not found`

**Comment by perbly** [comment]
Hitting some kind of bug https://github.com/traefik/traefik/issues/8345 that should be resolved in 2.4. Not really sure which version though. 2.4.13 was released 17 days ago and issue closed 5 days ago so probably fixed in a 2.4.14 release.

**Comment by perbly** [comment]
https://github.com/onify/install/commit/19e8e935e3eeb32dfcc50398a485be883002da65

**Comment by rolu01** [comment]
Thanks!
