### ISSUE TITLE
Support setting image version for Elasticsearch

### ISSUE THREAD

**Issue by rolu01** [onify/install#6]
It should be possible to set image version for ES (https://github.com/onify/install/blob/default/terraform/modules/onify-customer/elasticsearch.tf#L77)

Var can be called `elasticsearch_version`.

**Comment by perbly** [comment]
https://github.com/onify/install/commit/e8a877d9a40a5cf3519ed2d9108bf9ce19777f1c

**Comment by rolu01** [comment]
Thanks! Need to do some small changes to make it work: https://github.com/onify/install/commit/42b8daef07a98b341545f5eda0b7c2cd002ad631
